@startsalt
!include ../tema/uchile.puml

{+
    {T+
    + synth/ 
    ++ checkpoint/ 
    +++ copulagan.ckp 
    +++ <b><model></b>.ckp
    ++ data/
    +++ copulagan_21613.parquet
    +++ <b><model></b>_<b><n_sample></b>.parquet
    +++ privacy_copulagan_21613_SH.npy
    +++ privacy_copulagan_21613_ST.npy
    +++ privacy_<b><model></b>_<b><n_sample></b>_<b><type_comparison></b>.npy
    ++ report/
    +++ copulagan_21613.rpt
    +++ <b><model><b>_<b><n_sample></b>.rpt
    ++ split/
    +++ train.parquet
    +++ hold.parquet
    ++ metadata.json
    }
}
@endsalt